### ISSUE TITLE
Question on notes/dotfile integration

### ISSUE THREAD

**Issue by termlimit** [connermcd/dotfiles#1]
I recently watched your [Vim notetaking tips Youtube video](https://youtu.be/wh_WGWii7UE). I really liked the idea of your notes script.  I saw you used snippets to populate the file header.  Inspecting your dotfiles I don't see any reference to the snippets since your initial commits. They were quickly removed.  Are you no longer doing the headers and that is why you removed them or have you figured out a different solution?

Thanks! Sorry to open an issue, really had no other way to contact you.

**Comment by connermcd** [comment]
No worries! I don't have a different solution. I used those headers throughout medical school but now my notetaking style is different. I take notes on textbooks and articles rather than lectures, so I don't use those headers. I use BibTeX headers for books or articles and standard pandoc titles without snippets. I know there are several snippet plugins out there you could try if you're interesting though. Good luck!

**Comment by termlimit** [comment]
Thanks!!
